import { WindRhumb } from './wind-rhumb.interface';

export const WIND_RHUMBS: WindRhumb[] = [
  {
    id: 1,
    name: 'Северный',
    shortName: 'С',
    description:
      'Ветер с географического азимута 0° уходит в сторону 180°, а путевой угол на Лондон–Париж равен 148°, так что расхождение составляет всего 32°. Около 0,85 потока ложится в попутную составляющую и лишь 0,53 — в боковую, поэтому Boeing-737 NG идёт с прибавкой к путевой скорости и проходит маршрут быстрее штилевого расчёта.',
    imageKey: 'north_wind.jpg',
    videoKey: 'north_wind.mp4',
    status: 'published',
    rhumbGeographicAzimuthDeg: 0,
    rhumbMagneticAzimuthDeg: 348.5,
    likes: [1042, 1188, 1203, 1317, 1489, 1502, 1677],
  },
  {
    id: 2,
    name: 'Северо-восточный',
    shortName: 'СВ',
    description:
      'С географического азимута 45° поток идёт на 225°, то есть отклоняется от путевого угла 148° на 77° — почти прямой угол. Продольная составляющая остаётся крошечной, около 0,22, зато боковая доходит до 0,97. Время полёта Boeing-737 NG практически не меняется, но экипажу приходится держать заметный угол сноса.',
    imageKey: 'north_east_wind.jpg',
    videoKey: 'north_east_wind.mp4',
    status: 'published',
    rhumbGeographicAzimuthDeg: 45,
    rhumbMagneticAzimuthDeg: 33.5,
    likes: [1044, 1210, 1398, 1401],
  },
  {
    id: 3,
    name: 'Восточный',
    shortName: 'В',
    description:
      'Восточный румб направляет поток на 270°, расхождение с путевым углом 148° — 122°, то есть картина встречно-боковая. Против движения работает около 0,53 потока, поперёк — 0,85. Boeing-737 NG теряет на этом немного времени, а основная нагрузка ложится на удержание линии пути.',
    imageKey: 'east_wind.jpg',
    videoKey: 'east_wind.mp4',
    status: 'published',
    rhumbGeographicAzimuthDeg: 90,
    rhumbMagneticAzimuthDeg: 78.5,
    likes: [1007, 1156, 1289, 1344, 1470, 1512, 1583, 1611, 1702],
  },
  {
    id: 4,
    name: 'Юго-восточный',
    shortName: 'ЮВ',
    description:
      'Географический азимут 135° почти совпадает с путевым углом 148°: поток идёт на 315° и расходится с линией пути на 167°. Это практически чистый встречный ветер — 0,97 против движения и лишь 0,22 вбок. Из всех восьми румбов именно он отнимает у Boeing-737 NG больше всего времени на маршруте.',
    imageKey: 'south_east_wind.jpg',
    videoKey: 'south_east_wind.mp4',
    status: 'deleted',
    rhumbGeographicAzimuthDeg: 135,
    rhumbMagneticAzimuthDeg: 123.5,
    likes: [1099, 1231, 1355],
  },
  {
    id: 5,
    name: 'Южный',
    shortName: 'Ю',
    description:
      'Южный ветер дует в сторону 0°, а линия пути идёт на 148°, так что расхождение достигает 148° — ветер выраженно встречный. Около 0,85 потока тормозит Boeing-737 NG и 0,53 сносит его вбок, из-за чего перелёт Лондон–Париж заметно растягивается.',
    imageKey: 'south_wind.jpg',
    videoKey: 'south_wind.mp4',
    status: 'published',
    rhumbGeographicAzimuthDeg: 180,
    rhumbMagneticAzimuthDeg: 168.5,
    likes: [
      1013, 1128, 1264, 1330, 1442, 1519, 1608, 1690, 1721, 1804, 1877, 1902,
    ],
  },
  {
    id: 6,
    name: 'Юго-западный',
    shortName: 'ЮЗ',
    description:
      'С географического азимута 225° поток направлен на 45° и расходится с путевым углом 148° на 103° — это почти чистый боковик. Тормозящая составляющая мала, около 0,22, а поперечная доходит до 0,97. Время полёта Boeing-737 NG страдает слабо, зато снос на маршруте самый ощутимый.',
    imageKey: 'south_west_wind.jpg',
    videoKey: 'south_west_wind.mp4',
    status: 'published',
    rhumbGeographicAzimuthDeg: 225,
    rhumbMagneticAzimuthDeg: 213.5,
    likes: [1061, 1174, 1285, 1396, 1408, 1533],
  },
  {
    id: 7,
    name: 'Западный',
    shortName: 'З',
    description:
      'Западный румб гонит воздух на 90°, расхождение с путевым углом 148° — 58°, картина попутно-боковая. Примерно 0,53 потока прибавляется к путевой скорости и 0,85 идёт поперёк. Boeing-737 NG выигрывает время, но держит поправку на снос.',
    imageKey: 'west_wind.jpg',
    videoKey: 'west_wind.mp4',
    status: 'draft',
    rhumbGeographicAzimuthDeg: 270,
    rhumbMagneticAzimuthDeg: 258.5,
    likes: [1025, 1137, 1249, 1360, 1471, 1582, 1694, 1705],
  },
  {
    id: 8,
    name: 'Северо-западный',
    shortName: 'СЗ',
    description:
      'Географический азимут 315° разворачивает поток на 135°, а это всего 13° от путевого угла 148° — практически идеальный попутный ветер. В продольную составляющую уходит 0,97 потока и лишь 0,22 вбок. Именно этот румб даёт Boeing-737 NG наибольший выигрыш по времени на Лондон–Париж.',
    imageKey: 'north_west_wind.jpg',
    videoKey: 'north_west_wind.mp4',
    status: 'published',
    rhumbGeographicAzimuthDeg: 315,
    rhumbMagneticAzimuthDeg: 303.5,
    likes: [1082, 1193, 1305, 1416, 1528, 1639, 1740, 1851, 1963, 1974],
  },
];
